### ISSUE TITLE
01-HTML-GIT-CSS json terms

### ISSUE THREAD

**Issue by jpatterson933** [sofiatejada/vocab-list#3]
Put together list of terms for this seciton

**Comment by jpatterson933** [comment]
Alright basic list for 01 of potential terms

1. ls (a command used in the terminal)
2. mkdir (a command used in the terminal)
3. touch (a command used in the terminal)
4. cd (a command used in the terminal)
5. cd .. (a command used in the terminal)
6. pwd (a command used in the terminal)
7. Semantic HTML
8. HTML attributes
9. <section>
10. src attribute
11. alt attribute
12. href attribute
13. <h1> headers and such
14. <div>
15. <img>
16. <link>
17. CSS
18. Width
19. Height
20. font-family
21. line-height
22. background-color
23. color
24. Universal selector CSS
25. Selecting by HTML element
26. Selecting by class
27. Selecting by ID
28. CSS selectors in general
29. Pseudo-class selectors
30. Inline
31. Block
32. display and the different types
33. Border
34. Padding
35. Margin
36. text-align
37. position (relative, absolute, fixed)
38. top
39. right
40. bottom
41. left

**Comment by sofiatejada** [comment]
![Image](https://github.com/sofiatejada/vocab-list/assets/79775413/da6d9d22-dff1-48e6-99a9-b550dce5c91e)

Git cheat sheet

**Comment by sofiatejada** [comment]
![Image](https://github.com/sofiatejada/vocab-list/assets/79775413/440252cf-ba74-439f-88fa-e66253e16668)

Git stash stuff
