### ISSUE TITLE
create tests for basic react setup

### ISSUE THREAD

**Issue by jpatterson933** [sofiatejada/vocab-list#5]
Will most likely use this to ensure json data is consistent and is not missing any key value pairs

It is late but this is something I would like to have in place. Trying to force myself to work as a test driven developer hehe

**Comment by jpatterson933** [comment]
`Now I need to learn how to write tests for react lol`

**Comment by sofiatejada** [comment]
lol react testing library! i have examples of how to use it from my past code~
