### ISSUE TITLE
JSON data term structure

### ISSUE THREAD

**Issue by jpatterson933** [sofiatejada/vocab-list#9]
### need input

>term
>>formal definition
>>easy-to-understand
>>how to search
>>live example

json would look something like this

`{"term":"let", "formal definition": "The let declaration declares re-assignable, block-scoped local variables, optionally initializing each to a value.","easy-to-understand": "declare a changeable variable in javascript", "how-to-search": "javascript let", "live example": "click here for live example"}`

_I think for expediency purposes, we just work on everything except for the live example. We can always add it in later, but would be cool to get this to the class within the next week. Let me know what you think?_

**Comment by sofiatejada** [comment]
that looks good, we should just add a link to MDN, and W3 also. sometimes people understand one better over the other

**Comment by jpatterson933** [comment]
Can refer to issue #10 for agreed upon data structure.
